name: CI

on: push

permissions:
  contents: read
     
jobs:
    lint:
        runs-on: ubuntu-latest
        name: Protobuf lint
        container:
          image: bufbuild/buf:1.23.1
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - name: lint
              run:  buf lint
            - name: format
              run: buf format --exit-code
      
    fishjam_protos_lint:
        runs-on: ubuntu-latest
        name: CI elixir lint
        strategy:
          matrix:
            otp: ['27']
            elixir: ['1.17']
        steps:
            - name: Set up Elixir
              uses: erlef/setup-beam@v1
              with:
                otp-version: ${{matrix.otp}}
                elixir-version: ${{matrix.elixir}}
            - name: Checkout the code
              uses: actions/checkout@v3
              with:
                path: fishjam_protos
            - name: Install dependencies
              run: mix deps.get
              working-directory: fishjam_protos
            - name: Compile without warnings
              id: compile
              run: mix compile --warnings-as-errors
              working-directory: fishjam_protos
            - name: Check formatting
              if: ${{ !cancelled() && steps.compile.outcome == 'success' }}
              run: mix format --check-formatted
              working-directory: fishjam_protos
