name: CI

on: push

permissions:
  contents: read
     
jobs:
    lint:
        runs-on: ubuntu-latest
        name: Protobuf lint
        container:
          image: bufbuild/buf:1.23.1
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - name: lint
              run:  buf lint
            - name: format
              run: buf format --exit-code
