name: Deployment

permissions:
  contents: read

on:
  push:
    tags:
      - /v.*/

jobs:
  publish:
    runs-on: ubuntu-latest
    name: hex_publish
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          elixir-version: "1.17"

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: mix deps.get
        working-directory: fishjam_protos

      - name: Publish package
        env:
          HEX_API_KEY: ${{ secrets.MIX_HEX_KEY }}
        run: mix hex.publish --yes
        working-directory: fishjam_protos